### ISSUE TITLE
Payara 5.2021.8 bundles H2 1.4.200

### ISSUE THREAD

**Issue by donsizemore** [OdumInstitute/trsa-web#24]
This shouldn't affect Dataverse proper, but TRSA maintains its own external H2 DB, and it looks like there's trouble upgrading to 1.4.200. There is an `H2 Upgrade Helper` jar which may be of use when trsa-web prepares to update its version of H2. The only safe path may be `from script / to script` though. It is highly recommended that the H2 client version match that of the server.

**Comment by akio-sone** [comment]
As of 2022-01-07, the version of H2 Database specified in the pom.xml was updated to 2.0.206.
